// "use client";
// px json-server --port 9999 --watch db.json
import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";
import { Control } from "./Control";

export const metadata: Metadata = {
  title: "Web tutorials",
  description: "Generated by create honey",
};

export interface Topic {
  id: number;
  title: string;
  body: string;
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // const resp = await fetch("http://localhost:9999/topic", { next: { revalidate: 0 } });
  const resp = await fetch("http://localhost:9999/topic", { cache: "no-store" });
  const topics: Topic[] = (await resp.json()) ?? [];

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          <li>
            <Link href="/read/1">html</Link>
          </li>
          <li>
            <Link href="/read/2">css</Link>
          </li>
        </ol>

        <ol>
          {topics.map((el) => (
            <li key={el.id}>
              <Link href={`/read/${el.id}`}>{el.title}</Link>
            </li>
          ))}
        </ol>

        {children}
        <Control />
      </body>
    </html>
  );
}
